---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться в личном кабинете
  - Пользователь должен иметь возможность оформить заказ на добавленные в корзину товары и совершить оплату
  - Пользователь должен иметь возможность отслеживать статус оформленного заказа
  - Пользователь должен иметь возможность просматривать историю заказов
  - Пользователь должен иметь возможность обратиться к владельцу магазина с вопросом по товару или оформленному заказу
  - Пользователь должен иметь возможность удалять товары из корзины
